### ISSUE TITLE
Activity and organisation files missing

### ISSUE THREAD

**Issue by andreaszenasidi** [devinit/D-Portal#596] opened 2020-12-23 10:41 UTC
There are two publishers who reported via the IATI support desk that they are missing activity and organisation files in D-portal. These datasets exist in the IATI Registry. 

**1. [Women for Women International (UK) ](https://iatiregistry.org/publisher/wfwiuk)**
Missing activities:
https://d-portal.org/ctrack.html?reporting_ref=GB-CHC-1115109#view=act&aid=GB-CHC-1115109-F2JK-JZBU-GM
https://d-portal.org/ctrack.html?reporting_ref=GB-CHC-1115109#view=act&aid=GB-CHC-1115109-6XK9-WZGG-MN
Both activities exist in the registry:
https://iatiregistry.org/dataset/wfwiuk-activities

**2. [International Crisis Group](https://iatiregistry.org/publisher/crisisgroup)** 
Missing organisation file:
https://d-portal.org/ctrack.html?reporting_ref=US-EIN-52-5170039#view=main
The organisation file exists in the registry:
https://iatiregistry.org/dataset/crisisgroup-org

**Comment by notshi** [comment] 2020-12-24 20:35
Thanks for raising, @andreaszenasidi looks like some teething issues with the new server setup and database access.

There's been some major work done recently to the server when the hard drive needed replacement due to disk failure.
This meant upgrading libraries and crucial processes which included large and vital changes to the database architecture.

We've been keeping a close eye on the server and data imports, tweaking the server scripts to adjust it so that the server is not doing too many things, which can happen in parallel. In this case, there were too many database connections which caused failures in import.

We've updated the scripts and again, did a full re-import of the data and it looks like this latest code change has fixed the issues you raised.

We're going to run the scripts again and do a full import to make sure nothing goes amiss. This will take some time as **each full import takes about 5 hours to finish** so each code change takes equally long to check the effects.

Nonetheless, the links above should work as expected but do let us know if you find anything else missing.

**Comment by andreaszenasidi** [comment] 2020-12-30 15:46
@notshi thanks very much for the update! Unfortunately, there are still some issues reported by the publishers. They shared that they updated their data and this is not reflected in d-portal.

**1. [Danish Refugee Council](https://iatiregistry.org/publisher/drc)** 
They updated their data on the 28th of Dec but the data in d-portal shows last updated was 18th of Dec.
**d-portal:** https://d-portal.org/ctrack.html?reporting_ref=DK-CVR-20699310#view=act&aid=DK-CVR-20699310-DU22821
**Registry:** https://iatiregistry.org/dataset/drc-activities

**2. [Terre des hommes](https://iatiregistry.org/publisher/tdh_foundation)** 
Data updated Dec 28th, in d-portal the data is shown to be updated 17th of Dec.
**d-portal:** https://d-portal.org/ctrack.html#view=act&aid=CH-FDJP-CHE-106823242-20119723b
**Registry:** https://iatiregistry.org/dataset/tdh_foundation-activities

**3. [International Crisis Group](https://iatiregistry.org/publisher/crisisgroup)** 
The org file was updated Dec 24th but d-portal shows the Dec 17th version.
**d-portal:** https://d-portal.org/ctrack.html?reporting_ref=US-EIN-52-5170039#view=main
**Registry:** https://iatiregistry.org/dataset/crisisgroup-org

**4. [UNHCR](https://iatiregistry.org/publisher/unhcr)**
They reported they updated their data on Dec 24th, d-portal shows June 2020.
**d-portal:** https://d-portal.org/ctrack.html#view=act&aid=XM-DAC-41121-JPO
**Registry:** https://iatiregistry.org/dataset/unhcr-jpo

**5. [Ground Truth Solutions](https://iatiregistry.org/publisher/ground-truth-solutions)** 
They updated the data Dec 26th e.g. the name of the projects, which was updated in the Registry but not in d-portal, here Dec 22 is the last updated DateTime.
**d-portal:** https://d-portal.org/ctrack.html?reporting_ref=AT-UID-U74408937#view=list_activities
**Registry:** http://preview.iatistandard.org/index.php?url=https%3A//aidstream.s3.us-west-2.amazonaws.com/xml/ground-truth-solutions-activities.xml

Thanks in advance for the help!

**Comment by notshi** [comment] 2020-12-30 15:55
Thanks for sending these through @andreaszenasidi - really appreciate the concise notes.

I can confirm that we are still doing manual updates so we can keep an eye on what's changing and this is still part of the ongoing server fixes with the new hard drive.

The data should be live by tomorrow after tonight's full import and update.

**Comment by andreaszenasidi** [comment] 2020-12-30 15:58
@notshi Thanks for your fast reply! That sounds great, I will check the files tomorrow then. I will inform you if we still encounter any issues.

**Comment by andreaszenasidi** [comment] 2020-12-31 09:38
@notshi I just checked the above mentioned inconsistencies and all the data is up to date now. Thanks again for yesterdays update.

Just for me to better understand where things are now in case we get more inquiries, are you still working on server fixes or this is now fully resolved and d-portal is back to "normal" state? Many thanks!

**Comment by notshi** [comment] 2020-12-31 17:24
@andreaszenasidi Thanks for checking, that's good to know that all data is up to date as expected.

Technically, d-portal is back to 'normal' state now and valid data should be imported and be as up to date as the registry.

As mentioned before, a considerable amount of work was done to the server and databases. The last time we went through this installation process was over two years ago which meant as other bits of the server got newer, a lot of the services were no longer maintained and some of the libraries that we rely on became more and more deprecated so we took this opportunity to switch; the server now has a new operating system, new versions of nginx, node and postgresql.

As such, we are still adding scripts to the server but these are mostly part of maintenance and statistics for internal d-portal usage. These internal tools help us investigate where things go wrong when they do.

For example, [these logs](https://d-portal.org/ctrack.html?#view=dash_sluglog&slug=sida-af) tell us that we did not get the full file from that url due to a server error on their end so the publisher may be missing activities in their portal.

**Comment by andreaszenasidi** [comment] 2021-01-04 11:16
@notshi Thanks very much for clarifying where things are now and for the overall support with this issue!

**Comment by andreaszenasidi** [comment] 2021-01-05 13:08
@notshi Hi Shi, one of the publishers reported they still can't see their data in d-portal even though it shows up in the Registry. The data was published on December 23rd.

Registry: https://iatiregistry.org/publisher/undco
D-portal: https://d-portal.org/ctrack.html?reporting_ref=XM-DAC-%2041149#view=main

Would be great to understand what is the reason behind this. Many thanks for the help!

**Comment by xriss** [comment] 2021-01-05 13:32
Looks like a publisher ID problem.

XM-DAC-{there is a space here}41149 instead of XM-DAC-41149

That space is present in the registry data, so probably a typo when typing data in there and a dportal link without the space finds an activity.

https://d-portal.org/ctrack.html?reporting_ref=XM-DAC-41149#view=main

That space was present in the data we downloaded from the registry last night which you can find from searching for "undco" in this file ( which is a bit large as it contains data for all publishers on the registry )

https://github.com/devinit/D-Portal/blob/master/dstore/json/publishers.json

It looks like the registry is removing the space for display when previewing the data, which is probably not helpful. It should do that at the data level or not at all.

**Comment by andreaszenasidi** [comment] 2021-01-05 13:44
@xriss Thanks very much for the explanation!

**Comment by notshi** [comment] 2021-01-11 21:52
Hello @andreaszenasidi , is everything working as expected and we can close this issue?

**Comment by andreaszenasidi** [comment] 2021-01-12 09:08
@notshi Yes, everything works as expected. You can close this ticket. Many thanks for the help!

**Closed** 2021-01-12 11:09 UTC
Labels: bug
