### ISSUE TITLE
Activity page not showing/linking

### ISSUE THREAD

**Issue by amy-silcock** [devinit/D-Portal#468] opened 2018-06-04 10:43 UTC
Hi,

When I go to the list of Irise International's activities, the link to the individual activity page is not working: http://d-portal.org/ctrack.html?publisher=GB-CHC-1157722#view=active 

However, if I directly type in the URL for the Activity page it works fine: http://d-portal.org/ctrack.html?search&publisher=GB-CHC-1157722#view=act&aid=GB-CHC-1157722-UKAD'17 

Please could this be fixed?

Best wishes,

Amy

**Comment by andylolz** [comment] 2018-06-04 12:07
Looks like the quote mark towards the end of the IATI identifier is playing havoc. (But as we know, the standard doesn’t say it’s invalid.)

I guess the issue is here?

https://github.com/devinit/D-Portal/blob/49447c0ecd1a1d4c820006ecb339e5fce35716b6/ctrack/js/view_list_activities.js#L101

`encodeURIComponent` doesn’t escape quote marks. (`escape` does, but `escape` appears to be broken in other ways.)

**Comment by k8hughes** [comment] 2018-09-21 11:33
Is there a quick fix for this?
We have also contacted the organisation and asked them to fix their IATI identifier.

**Comment by andylolz** [comment] 2018-09-21 11:45
> We have also contacted the organisation and asked them to fix their IATI identifier.

It might cause problems for tools, but this identifier is valid according to the standard. Asking publishers to fix stuff that’s valid sets a bad precedent.

**Comment by xriss** [comment] 2018-09-21 20:07
I think this is probably fixed as I've changed the escaping and how the hash part of URLs is processed as this seemed to *also* be part of the problem on firefox .

see https://bugzilla.mozilla.org/show_bug.cgi?id=1213870

FYI you also can not trust the URL displayed by firefox as it may have tampered with it, this caused considerable confusion when I tried to work out what was going on.

**Comment by amy-silcock** [comment] 2018-09-24 13:29
@xriss great to see this now working in Chrome and IE

**Comment by coneyislander** [comment] 2018-12-06 08:50
Probably a similar issue to the one described here - I filtered data by a free text search term, then downloaded CSV of all hits, but links (in column 'links' e.g. http://d-portal.org/ctrack.html#view=act&aid=44000-P085374) lead to http://d-portal.org/ctrack.html#view=search (not the activity specific page).
--

**Comment by notshi** [comment] 2018-12-19 14:40
This is also working in Firefox.

Thanks for reporting, @coneyislander but that looks like a different issue (not clicking a link from the website) but clicking a link from an external application.

I'll move this to a new issue.

**Closed by notshi** 2018-12-19 14:40 UTC
Labels: Data
