### ISSUE TITLE
Multi-Language activities in d-portal issue (raised by UNHCR)

### ISSUE THREAD

**Issue by amy-silcock** [devinit/D-Portal#560] opened 2020-04-27 13:57 UTC
Firstly congratulations on the recent upgrade to d-portal. There are lots of improvements, notably the sector breakdown.

An issue has been introduced with the languages.

UNHCR publish the title and description text in the local language where possible (as recommended!) and in English and French (the two languages used widely in UNHCR).

In the past, d-portal showed the titles and descriptions in all published languages.

Now however, it’s only publishing one, and the choice of language seems to come from the order the languages are in the XML. For example, here are the activities for Jordan and Spain. The activity for Jordan has the title in English, French and Arabic, and the activity for Spain has the title in English, French and Spanish.

https://d-portal.org/ctrack.html?reporting_ref=XM-DAC-41121&tongue=eng#view=act&aid=XM-DAC-41121-2020-MENA-JOR

![image](https://user-images.githubusercontent.com/27764077/80380262-3a6eca80-8897-11ea-8afe-924eefca02bb.png)

https://d-portal.org/ctrack.html?reporting_ref=XM-DAC-41121&tongue=eng#view=act&aid=XM-DAC-41121-2020-EUR-ESPMCO

![image](https://user-images.githubusercontent.com/27764077/80380277-422e6f00-8897-11ea-8061-1994c4428535.png)

Mostly, English appears and not the other languages. However Arabic appears over English I think just because AR comes before EN in the alphabet.

I see the “Parameters” setting at the top don’t change the data displayed. I was thinking maybe if I chose French it will display the title in French. Alas, no, that only affects the navigation lables.

 
![image](https://user-images.githubusercontent.com/27764077/80380326-55413f00-8897-11ea-94ea-1a3b0133e937.png)

Can this be checked please.

**Comment by stevieflow** [comment] 2020-04-27 14:42
This is a duplicate of https://github.com/devinit/D-Portal/issues/558

**Comment by notshi** [comment] 2020-04-30 19:34
Thanks, @amy-silcock - multiple narratives are now displayed.

We hope to connect this to the language setting parameter but will need some time allocated to work on it as it needs consideration in terms of design structure of the whole site.

**Comment by stevieflow** [comment] 2020-05-05 11:16
> We hope to connect this to the language setting parameter but will need some time allocated to work on it as it needs consideration in terms of design structure of the whole site.

I think this is a whole other thing, and should be considered as so, away from this ticket.

**Comment by notshi** [comment] 2020-05-05 15:17
Thanks, @stevieflow that was implied :}

**Comment by notshi** [comment] 2020-09-22 13:36
Closing because multi-language support is working. Please re-open if that is not the case.

**Closed by notshi** 2020-09-22 13:36 UTC
