### ISSUE TITLE
Question about transaction graphs

### ISSUE THREAD

**Issue by amy-silcock** [devinit/D-Portal#524] opened 2019-07-09 09:00 UTC
Hi guys,

I've received the question below from an IATI publisher. He's wondering why graphs of transaction types don't always appear. I looks like if there area mix of currencies within the transactions then no graphs are displayed? This logic fits the examples below.

Is this correct?

If yes, is there a way of doing a currency conversion to the default currency to allow the graphs to show? If not, do you know why the graphs aren't showing?

Many thanks,

Amy

---------------------------------------------------

I’ve noticed that sometimes the d-portal shows a nice chart of transactions, and sometime not.

 

See:
![image](https://user-images.githubusercontent.com/27764077/60874465-fe974580-a22f-11e9-9a2c-11ab08a1fbc5.png)

 

from:

http://d-portal.org/ctrack.html?publisher=XM-DAC-41121#view=act&aid=XM-DAC-41121-2018-JPO

 

 

But then ...

 
![image](https://user-images.githubusercontent.com/27764077/60874476-02c36300-a230-11e9-9804-2fb4a787e2dd.png)

 

From:

http://d-portal.org/ctrack.html?publisher=XM-DAC-41121#view=act&aid=XM-DAC-41121-2018-MENA-YEM

 

I can’t see anything that could cause the difference. There is a larger time-frame for transactions for the JPO programme than for Yemen so it doesn’t look like that is the reason.

 

Is there a known problem with d-portal that can cause this ? Or can you spot something incorrect in the XML ?

 

With many thanks in advance for your help,

 

Justin

**Comment by xriss** [comment] 2019-07-09 17:22
Hi @amy-silcock,

Yes, if the currencies are mixed then it does not try to display any graphs. We advice not mixing currencies if publishers want to see these graphs displayed.

Currency conversion is difficult (and complex) to get right, especially as the views are calculated browser side from the raw IATI data; ie. it processes the raw XML in real time. The initial intention with SAVi was to display the published data as is, rather than try and fix or convert it. To change that would require a complete rewrite.

This will only give estimates and the numbers may even fluctuate if you view the same page on a different day - there is also the problem of getting conversion rates for future dates (in planned disbursements). And if there are multiple currencies, which gets prioritised as the default?

As for transaction graphs:
The transactions are all on the same date, which is causing the graphs to get a little bit confused.

The data is there but it is just a dot on the far right hand side, so far right in fact that it has been clipped from the display. Will take a look at fixing this but the problem is in the data.

**Comment by JoshStanleyDevInit** [comment] 2019-08-08 10:59
Hi @xriss,

Catholic Relief Services have raised a similar query about the transactions graph and currencies.

On this activity - https://d-portal.org/ctrack.html?publisher=US-EIN-13-5563422#view=act&aid=US-EIN-13-5563422-8960100 - the Incoming Commitment is in GBP and the rest of the transactions are in USD.

However in this case, all transactions are shown on the main graph, including the 170k incoming commitment. My understanding was that if the currencies differ, then they aren't displayed. Can you advise why this might be?

Thanks,
Josh

**Comment by xriss** [comment] 2019-08-08 22:25
Thank you,

That looks like a bug, it should not try and display graph due to the mixed currencies.

This is now fixed.

**Comment by stevieflow** [comment] 2019-09-18 17:59
I was also trying to understand this via NRGI, so thanks @amy-silcock for spotting it, and @xriss & @JoshStanleyDevInit for further discussions

http://d-portal.org/q.html?aid=US-EIN-20-4451390-DFIDAG001 is in the same situation, which is a slight shame, as there are a lot of transactions!

I guess an issue underneath this is that organisations are required (I think) by their donor (DFID, in this case) to publish incoming flows in the donor currency.  Hence, if their outflows are not in this currency, it is legitimate scenario - but they lose this d-portal goodness.  

Thanks @xriss for the explanation - very understandable.  Maybe this should be flagged on activity pages or in the FAQ on d-portal to help users understand this.  Ultimately however, I cant see how this can be fixed

**Comment by notshi** [comment] 2021-02-17 12:47
Closing as this is now a duplicate of #556

**Closed by notshi** 2021-02-17 12:47 UTC
Labels: Data, question

**Comment by stevieflow** [comment] 2024-03-20 17:17
I added something "new" around this here https://github.com/IATI/D-Portal/issues/665-
